name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: ^5.4.0
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: 'ContactMe'


flutter:


  uses-material-design: true
  assets:
    - images/img.jpg

  fonts:
   - family: ComforterBrush
     fonts:
      - asset: fonts/ComforterBrush-Regular.ttf
   - family: SourceSansPro
     fonts:
      - asset: fonts/SourceSansPro-ExtraLight.ttf


